### ISSUE TITLE
Throw error from property in Swift 5.5

### ISSUE THREAD

**Issue by rogerluan** [JARMourato/Injection#3]
https://github.com/JARMourato/Injection/blob/62ce35fb44fbd64f44aa856b693f2d3f09d41cca/Sources/Injection.swift#L95

https://www.swiftbysundell.com/articles/throwing-async-properties/

**Comment by JARMourato** [comment]
looking forward to make this change 🎉

**Comment by JARMourato** [comment]
apparently it is not possible for property wrappers @rogerluan

**Comment by rogerluan** [comment]
Sad 😢 
Thanks for checking!
